### ISSUE TITLE
Translate `/models/finding-records.md`, Ember 4.7

### ISSUE THREAD

**Issue by BlueCutOfficial** [DazzlingFugu/ember-fr-guides-source#74]
Please assign yourself to the issue or let a comment at the very moment you start the translation.<br><br>File: `guides/release/models/finding-records.md`<br>From Ember: **N/A**<br>To: **4.7**

**Comment by Noctambul** [comment]
Hello, I'd like to start translating this page

**Comment by BlueCutOfficial** [comment]
Sorry for not answering here sooner @Noctambul I am not very good at following my Github notifications and I just missed that :3  It's awesome that you opened the PR 🙏
