### ISSUE TITLE
Translate `/models/creating-updating-and-deleting-records.md`, Ember 4.7

### ISSUE THREAD

**Issue by BlueCutOfficial** [DazzlingFugu/ember-fr-guides-source#95]
Please assign yourself to the issue or let a comment at the very moment you start the translation.<br><br>File: `guides/release/models/creating-updating-and-deleting-records.md`<br>From Ember: **N/A**<br>To: **4.7**

**Comment by Noctambul** [comment]
Hi, I start translating this page

**Comment by AnChopin** [comment]
Hello, I take over Noctambul to translate this page
